/**
 * WebRajya POS - Production Data Hygiene & Classification Engine
 * 
 * Classifies all database records into:
 * - PRODUCTION: Legitimate operational business data
 * - DEMO: Sample catalog data provided out-of-the-box for venue demonstration
 * - TEST: Records generated by automated test runners or manual QA passes
 * - UNKNOWN: Unclassified records requiring manual administrative review
 * 
 * Safely performs audits without blindly destroying records.
 */

import fs from 'fs';
import path from 'path';

export type DataClassification = 'PRODUCTION' | 'DEMO' | 'TEST' | 'UNKNOWN';

export interface ClassifiedRecord {
  id: string;
  type: 'order' | 'menu_item' | 'ingredient' | 'recipe' | 'supplier' | 'purchase' | 'wastage' | 'transaction' | 'audit_log';
  classification: DataClassification;
  identifier: string;
  reason: string;
  createdAt?: string;
  businessId?: string;
}

export interface HygieneAuditReport {
  timestamp: string;
  totalRecordsScanned: number;
  summary: Record<DataClassification, number>;
  breakdown: Record<string, Record<DataClassification, number>>;
  flaggedTestRecords: ClassifiedRecord[];
}

export class ProductionDataHygiene {
  private static STORE_PATH = path.join(process.cwd(), 'db-store.json');

  /**
   * Classify an order record
   */
  public static classifyOrder(order: any): ClassifiedRecord {
    const id = String(order.id || '');
    const customer = String(order.customerName || '').toLowerCase();
    const phone = String(order.phoneNumber || '');

    let classification: DataClassification = 'PRODUCTION';
    let reason = 'Live customer transaction';

    if (
      id.includes('TEST') || 
      id.includes('QA') || 
      id.includes('BENCH') ||
      id.includes('E2E') ||
      id.includes('MOCK') ||
      customer.includes('test') || 
      customer.includes('qa runner') ||
      customer.includes('benchmark') ||
      phone === '9999999999' ||
      phone === '0000000000'
    ) {
      classification = 'TEST';
      reason = 'Generated during automated QA or testing';
    } else if (
      customer.includes('demo') ||
      customer.includes('sample customer') ||
      id.startsWith('DEMO-')
    ) {
      classification = 'DEMO';
      reason = 'Sample demonstration order';
    }

    return {
      id: order.id,
      type: 'order',
      classification,
      identifier: `${order.id} (${order.customerName || 'Unknown'})`,
      reason,
      createdAt: order.createdAt,
      businessId: order.businessId || order.restaurantId
    };
  }

  /**
   * Classify an ingredient record
   */
  public static classifyIngredient(ing: any): ClassifiedRecord {
    const id = String(ing.id || '');
    const name = String(ing.name || '').toLowerCase();

    let classification: DataClassification = 'PRODUCTION';
    let reason = 'Active kitchen ingredient';

    if (
      id.includes('test') || 
      id.includes('qa') || 
      id.includes('e2e') ||
      name.includes('test') || 
      name.includes('qa') ||
      name.includes('mock') ||
      name.includes('benchmark')
    ) {
      classification = 'TEST';
      reason = 'QA simulation ingredient';
    } else if (
      name.includes('sample') || 
      id.startsWith('demo-')
    ) {
      classification = 'DEMO';
      reason = 'Demo starter ingredient';
    }

    return {
      id: ing.id,
      type: 'ingredient',
      classification,
      identifier: `${ing.name} [${ing.unit}]`,
      reason,
      createdAt: ing.createdAt,
      businessId: ing.businessId
    };
  }

  /**
   * Classify a recipe record
   */
  public static classifyRecipe(recipe: any): ClassifiedRecord {
    const id = String(recipe.id || '');
    const name = String(recipe.recipeName || recipe.name || '').toLowerCase();
    const menuItemId = String(recipe.menuItemId || '');

    let classification: DataClassification = 'PRODUCTION';
    let reason = 'Menu item bill of materials';

    if (
      id.includes('test') || 
      id.includes('qa') || 
      id.includes('e2e') ||
      name.includes('test') || 
      name.includes('qa') || 
      menuItemId.includes('test')
    ) {
      classification = 'TEST';
      reason = 'QA test recipe';
    } else if (name.includes('demo') || menuItemId.includes('demo')) {
      classification = 'DEMO';
      reason = 'Demo recipe';
    }

    return {
      id: recipe.id,
      type: 'recipe',
      classification,
      identifier: `${recipe.recipeName || recipe.name || recipe.menuItemId}`,
      reason,
      createdAt: recipe.createdAt,
      businessId: recipe.businessId
    };
  }

  /**
   * Classify a purchase record
   */
  public static classifyPurchase(purchase: any): ClassifiedRecord {
    const id = String(purchase.id || '');
    const invoiceNumber = String(purchase.invoiceNumber || '').toLowerCase();

    let classification: DataClassification = 'PRODUCTION';
    let reason = 'Operational supplier purchase';

    if (
      id.includes('test') || 
      id.includes('qa') || 
      invoiceNumber.includes('test') || 
      invoiceNumber.includes('qa') ||
      invoiceNumber.includes('inv-qa-')
    ) {
      classification = 'TEST';
      reason = 'Automated QA purchase test';
    } else if (invoiceNumber.includes('demo')) {
      classification = 'DEMO';
      reason = 'Demo sample purchase';
    }

    return {
      id: purchase.id,
      type: 'purchase',
      classification,
      identifier: `Invoice #${purchase.invoiceNumber}`,
      reason,
      createdAt: purchase.purchaseDate || purchase.createdAt,
      businessId: purchase.businessId
    };
  }

  /**
   * Run a comprehensive audit of the local store
   */
  public static runAudit(): HygieneAuditReport {
    if (!fs.existsSync(this.STORE_PATH)) {
      return {
        timestamp: new Date().toISOString(),
        totalRecordsScanned: 0,
        summary: { PRODUCTION: 0, DEMO: 0, TEST: 0, UNKNOWN: 0 },
        breakdown: {},
        flaggedTestRecords: []
      };
    }

    const raw = fs.readFileSync(this.STORE_PATH, 'utf-8');
    const store = JSON.parse(raw);

    const report: HygieneAuditReport = {
      timestamp: new Date().toISOString(),
      totalRecordsScanned: 0,
      summary: { PRODUCTION: 0, DEMO: 0, TEST: 0, UNKNOWN: 0 },
      breakdown: {
        orders: { PRODUCTION: 0, DEMO: 0, TEST: 0, UNKNOWN: 0 },
        menuItems: { PRODUCTION: 0, DEMO: 0, TEST: 0, UNKNOWN: 0 },
        inventory: { PRODUCTION: 0, DEMO: 0, TEST: 0, UNKNOWN: 0 },
        auditLogs: { PRODUCTION: 0, DEMO: 0, TEST: 0, UNKNOWN: 0 }
      },
      flaggedTestRecords: []
    };

    // Scan Orders
    if (Array.isArray(store.orders)) {
      for (const order of store.orders) {
        const classified = this.classifyOrder(order);
        report.totalRecordsScanned++;
        report.summary[classified.classification]++;
        report.breakdown.orders[classified.classification]++;
        if (classified.classification === 'TEST') {
          report.flaggedTestRecords.push(classified);
        }
      }
    }

    // Scan Inventory items
    if (Array.isArray(store.inventory)) {
      for (const item of store.inventory) {
        const classified = this.classifyIngredient(item);
        report.totalRecordsScanned++;
        report.summary[classified.classification]++;
        report.breakdown.inventory[classified.classification]++;
        if (classified.classification === 'TEST') {
          report.flaggedTestRecords.push(classified);
        }
      }
    }

    // Scan Audit Logs
    if (Array.isArray(store.auditLogs)) {
      for (const log of store.auditLogs) {
        const action = String(log.action || '').toLowerCase();
        const details = String(log.details || '').toLowerCase();
        let cls: DataClassification = 'PRODUCTION';
        let reason = 'Operational system audit';

        if (action.includes('test') || details.includes('test') || details.includes('qa')) {
          cls = 'TEST';
          reason = 'Test run audit entry';
        }

        report.totalRecordsScanned++;
        report.summary[cls]++;
        report.breakdown.auditLogs[cls]++;
        if (cls === 'TEST') {
          report.flaggedTestRecords.push({
            id: log.id,
            type: 'audit_log',
            classification: cls,
            identifier: log.action,
            reason,
            createdAt: log.timestamp
          });
        }
      }
    }

    return report;
  }
}

// CLI Execution if executed directly
if (typeof process !== 'undefined' && process.argv[1]?.endsWith('production-data-hygiene.ts')) {
  const audit = ProductionDataHygiene.runAudit();
  console.log('======================================================');
  console.log('WEBRAJYA POS - PRODUCTION DATA HYGIENE AUDIT REPORT');
  console.log('======================================================');
  console.log(`Audit Timestamp : ${audit.timestamp}`);
  console.log(`Records Scanned : ${audit.totalRecordsScanned}`);
  console.log('Classification Summary:');
  console.log(`  - PRODUCTION  : ${audit.summary.PRODUCTION}`);
  console.log(`  - DEMO        : ${audit.summary.DEMO}`);
  console.log(`  - TEST (Mock) : ${audit.summary.TEST}`);
  console.log(`  - UNKNOWN     : ${audit.summary.UNKNOWN}`);
  console.log('------------------------------------------------------');
  console.log(`Flagged QA/Test Records: ${audit.flaggedTestRecords.length}`);
  for (const item of audit.flaggedTestRecords.slice(0, 5)) {
    console.log(`  [${item.type.toUpperCase()}] ${item.identifier} -> Reason: ${item.reason}`);
  }
  if (audit.flaggedTestRecords.length > 5) {
    console.log(`  ... and ${audit.flaggedTestRecords.length - 5} more records.`);
  }
  console.log('======================================================');
}
